[theme]


[server]


[browser]
gatherUsageStats = false  # This removes the "Made with Streamlit" footer


[client]
showSidebarNavigation = false  

[footer]
hideStreamlitFooter = true  # Removes the "Made with Streamlit"
